const testMapData = {
    widthInTiles: 3,
    heightInTiles: 3,
    tileData: [
        // ----- floor -----
        { x: 0, y: 0, layer: "floor", type: "sidewalk", variation: true },
        { x: 0, y: 1, layer: "floor", type: "sidewalk", variation: true },
        { x: 0, y: 2, layer: "floor", type: "sidewalk", variation: true },
        { x: 0, y: 3, layer: "floor", type: "sidewalk", variation: true },
        { x: 0, y: 4, layer: "floor", type: "sidewalk", variation: true },
        { x: 0, y: 5, layer: "floor", type: "sidewalk", variation: true },
        { x: 0, y: 6, layer: "floor", type: "sidewalk", variation: true },
        { x: 0, y: 7, layer: "floor", type: "sidewalk", variation: true },
        { x: 0, y: 8, layer: "floor", type: "sidewalk", variation: true },

        { x: 1, y: 0, layer: "floor", type: "sidewalk", variation: true },
        { x: 1, y: 1, layer: "floor", type: "sidewalk", variation: true },
        { x: 1, y: 2, layer: "floor", type: "sidewalk", variation: true },
        { x: 1, y: 3, layer: "floor", type: "sidewalk", variation: true },
        { x: 1, y: 4, layer: "floor", type: "sidewalk", variation: true },
        { x: 1, y: 5, layer: "floor", type: "sidewalk", variation: true },
        { x: 1, y: 6, layer: "floor", type: "sidewalk", variation: true },
        { x: 1, y: 7, layer: "floor", type: "sidewalk", variation: true },
        { x: 1, y: 8, layer: "floor", type: "sidewalk", variation: true },

        { x: 2, y: 0, layer: "floor", type: "sidewalk", variation: true },
        { x: 2, y: 1, layer: "floor", type: "sidewalk", variation: true },
        { x: 2, y: 2, layer: "floor", type: "sidewalk", variation: true },
        { x: 2, y: 3, layer: "floor", type: "sidewalk", variation: true },
        { x: 2, y: 4, layer: "floor", type: "sidewalk", variation: true },
        { x: 2, y: 5, layer: "floor", type: "sidewalk", variation: true },
        { x: 2, y: 6, layer: "floor", type: "sidewalk", variation: true },
        { x: 2, y: 7, layer: "floor", type: "sidewalk", variation: true },
        { x: 2, y: 8, layer: "floor", type: "sidewalk", variation: true },

        { x: 3, y: 0, layer: "floor", type: "sidewalk", variation: true },
        { x: 3, y: 1, layer: "floor", type: "sidewalk", variation: true },
        { x: 3, y: 2, layer: "floor", type: "sidewalk", variation: true },
        { x: 3, y: 3, layer: "floor", type: "sidewalk", variation: true },
        { x: 3, y: 4, layer: "floor", type: "sidewalk", variation: true },
        { x: 3, y: 5, layer: "floor", type: "sidewalk", variation: true },
        { x: 3, y: 6, layer: "floor", type: "sidewalk", variation: true },
        { x: 3, y: 7, layer: "floor", type: "sidewalk", variation: true },
        { x: 3, y: 8, layer: "floor", type: "sidewalk", variation: true },

        { x: 4, y: 0, layer: "floor", type: "sidewalk", variation: true },
        { x: 4, y: 1, layer: "floor", type: "sidewalk", variation: true },
        { x: 4, y: 2, layer: "floor", type: "sidewalk", variation: true },
        { x: 4, y: 3, layer: "floor", type: "sidewalk", variation: true },
        { x: 4, y: 4, layer: "floor", type: "sidewalk", variation: true },
        { x: 4, y: 5, layer: "floor", type: "sidewalk", variation: true },
        { x: 4, y: 6, layer: "floor", type: "sidewalk", variation: true },
        { x: 4, y: 7, layer: "floor", type: "sidewalk", variation: true },
        { x: 4, y: 8, layer: "floor", type: "sidewalk", variation: true },
    ]
}